name: marketlens
display_name: MarketLens
description: A Flutter application for financial news.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.5
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  webview_flutter: ^4.4.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
